#!/bin/bash
# arm_certify.sh — prove a freshly deployed arm ENCODES CONFORMING BYTES,
# in 3 seconds, once, at deploy time.
#
# WHY THIS EXISTS, AND WHY IT IS NOT IN e_gate_run.sh (owner directive,
# 2026-08-01).
#
# The wire audit and the black-frame decode were built as standalone
# forensics — one on 2026-07-28 to answer "is the aux view really
# inter-compressed?" from bitstream syntax rather than from the encoder's
# own logs, one on 2026-07-29 as the owner's gate after two builds
# reached the Mac flashing black. Both were folded into e_gate_run.sh the
# same week (3d09fdb7), unconditionally, when an oracle dump was 83 MB
# and walking it twice was free.
#
# It stopped being free. At 3840x2400 a 60 s run dumps 7.75 GB, and the
# two walks — parsing every slice header of 4448 pictures, then decoding
# all 4448 — took 10 min 07 s against 64 s of actual measurement. A 10x
# tax on every timing experiment, to re-prove properties that had not
# changed.
#
# WHAT THESE CHECKS ARE A PROPERTY OF (the owner's correction, and the
# whole reason this file exists): NOT the xrdp build. The rewriter logic
# is covered by CI — tests/xrdp/test_avc444_ltr.c pins it against 26
# golden-vector assertions, byte-exact, generated by ltr_splice_ref.py.
# What an ARM adds on top of that is the real stack actually producing
# bytes: this image's ffmpeg, this host's VAAPI driver, this arm's
# gfx.toml encoder_args. That is a property of the DEPLOYED PAIR, so it
# is proven ONCE when the pair is deployed and never again.
#
#   CI              the rewriter is correct                 every commit
#   arm_certify.sh  this image + config emits conforming    every deploy
#                   bytes through the real encoder
#   e_gate_run.sh   how fast it goes                        every measurement
#
# THE RULE: 3 seconds of payload after a container deploy, and NOWHERE
# ELSE. A measurement run does not dump and does not walk a dump.
#
# Usage: arm_certify.sh <arm> [port]      (port defaults from k8s/<arm>.yaml)
set -u
D=$(cd "$(dirname "$0")" && pwd)
ARM=${1:?usage: arm_certify.sh <arm> [port]}
NS=${E_NS:-bisect-matrix}
SECS=${CERT_SECS:-3}
REFRESH=${E_REFRESH:-240}
CLI=${E_DISPLAY:-:94}
ORACLE_BIN=${E_ORACLE_BIN:-/opt/freerdp-vaapi/bin/xfreerdp}
CRED=${E_CRED_FILE:-/root/.oracle_cred}
SU=${E_USER:-probe444}
CERTDIR=$D/certs
SIZE=${CERT_SIZE:-1920x1080}

PORT=${2:-$(sed -n 's/^ *hostPort: *//p' "$D/k8s/$ARM.yaml" | head -1)}
[ -n "$PORT" ] || { echo "ABORT: no hostPort for $ARM" >&2; exit 1; }

fail() { echo "CERT ABORT: $*" >&2; exit 1; }

[ -x "$ORACLE_BIN" ] || fail "oracle client missing at $ORACLE_BIN"
[ -s "$CRED" ] || fail "no RDP credential at $CRED"

POD=$(kubectl -n "$NS" get pod -l "arm=$ARM" --field-selector \
        status.phase=Running -o jsonpath='{.items[0].metadata.name}' \
        2>/dev/null)
[ -n "$POD" ] || fail "no running pod for $ARM"

# The certificate is keyed to the exact thing under test. If either the
# image or the config changes, the old certificate must not be readable
# as covering the new pair -- that is the same failure the ARM_TAG /
# manifest pin guard exists for.
IMAGE=$(kubectl -n "$NS" get pod "$POD" \
        -o jsonpath='{.spec.containers[0].image}')
GFXSUM=$(sha256sum "$D/gfx/$ARM.toml" | cut -c1-16)
KEY="$IMAGE|$GFXSUM"

mkdir -p "$CERTDIR"
CERT=$CERTDIR/$ARM.cert
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

echo "certifying $ARM ($POD) — ${SECS}s of payload at $SIZE"
echo "  image  $IMAGE"
echo "  gfx    sha256:$GFXSUM"

# --- client rig: stateless, same rule as the gate (2026-07-31) ---------
XPID=$(cat "/tmp/.X${CLI#:}-lock" 2>/dev/null | tr -d ' ')
if [ -n "$XPID" ] && kill -0 "$XPID" 2>/dev/null; then
    kill -TERM "$XPID" 2>/dev/null
    for _ in 1 2 3 4 5; do kill -0 "$XPID" 2>/dev/null || break; sleep 1; done
fi
setsid Xorg "$CLI" -config "$D/../multimon_offline/xorg-dummy-2mon-4k.conf" \
    -noreset -logfile "$WORK/xorg.log" </dev/null >/dev/null 2>&1 &
XPID=$!
sleep 4

PW=$(cat "$CRED")
RDPARGS=$(printf '%s\n' "/v:127.0.0.1:$PORT" "/u:$SU" "/p:$PW" \
                        "/size:$SIZE" "/gfx:AVC444" "/cert:ignore" \
                        "/log-level:WARN")
rm -f /tmp/oracle_avc_s*.bin
setsid env DISPLAY=$CLI LD_LIBRARY_PATH=/opt/freerdp-vaapi/lib \
    FREERDP_ORACLE_DUMP=1 RDPARGS="$RDPARGS" \
    "$ORACLE_BIN" /args-from:env:RDPARGS </dev/null \
    >"$WORK/client.log" 2>&1 &
PGID=$!
unset PW RDPARGS
sleep "$SECS"
kill -9 -- -"$PGID" 2>/dev/null
sleep 1
kill -TERM "$XPID" 2>/dev/null

DUMP=$(ls -S /tmp/oracle_avc_s*.bin 2>/dev/null | head -1)
if [ -z "$DUMP" ]; then
    # keep the evidence: a no-dump certification is a red result about
    # the arm, and its client log is the only thing that says why
    cp "$WORK/client.log" "$CERTDIR/$ARM.nodump.log" 2>/dev/null
    fail "$ARM produced no dump in ${SECS}s — it is not encoding at all; \
client log kept at $CERTDIR/$ARM.nodump.log"
fi
mv "$DUMP" "$WORK/cert.bin"
DUMP=$WORK/cert.bin
BYTES=$(stat -c %s "$DUMP")

{
    echo "arm:    $ARM"
    echo "image:  $IMAGE"
    echo "gfx:    sha256:$GFXSUM"
    echo "key:    $KEY"
    echo "when:   $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "window: ${SECS}s at $SIZE, $BYTES bytes"
    echo
    echo "=== wire audit (--assert) ==="
    python3 "$D/../../tools/avc444_ltr_wire_audit.py" --assert \
        --intra-refresh "$REFRESH" "$DUMP" "$ARM deploy certification" \
        2>&1 | tail -25
    WA=$?
    echo "wire audit exit: $WA"
    echo
    echo "=== black-frame check ==="
    python3 "$D/oracle_black_frame_check.py" "$DUMP" 2>&1 | tail -15
    echo
    echo "=== COVERAGE LIMIT OF A ${SECS}s WINDOW — read this ==="
    echo "A ${SECS}s window holds roughly 100 frames. The scheduled intra"
    echo "refresh is every $REFRESH frames, so this certification"
    echo "typically contains NO scheduled cut, and asserts A2 (intra only"
    echo "on a scheduled index), A3 (cuts paired across views) and A4 (no"
    echo "scheduled cut skipped) VACUOUSLY. What it does prove on real"
    echo "bytes from this image: A1 no mid-stream IDR, A5 own-slot refs"
    echo "and self-marking, A6 one contiguous frame_num chain, A7 chain"
    echo "depth within bound, and that every picture decodes without a"
    echo "black frame."
    echo "The cut schedule itself is covered by CI against golden vectors"
    echo "(tests/xrdp/test_avc444_ltr.c: test_ltr_dpb_scheduled_paired_cut"
    echo "_both_modes, test_ltr_schedule_observed_vs_requested,"
    echo "test_ltr_cut_sequence_byte_exact). Do NOT lengthen this window"
    echo "to chase A2-A4 -- that is the 10x tax this file exists to"
    echo "remove, and CI already pins the logic byte-exactly."
} > "$CERT.tmp" 2>&1

if grep -q "ASSERT VERDICT: PASS" "$CERT.tmp" \
        && grep -q "VERDICT: PASS" "$CERT.tmp"; then
    mv "$CERT.tmp" "$CERT"
    echo "CERTIFIED: $ARM -> $CERT"
    exit 0
fi
mv "$CERT.tmp" "$CERT.FAILED"
echo "NOT CERTIFIED: $ARM — see $CERT.FAILED" >&2
echo "  the arm encodes non-conforming or undecodable bytes; do not" >&2
echo "  measure it. A red result stays red." >&2
exit 1
