#!/bin/bash
# arm_certify.sh — prove a freshly deployed arm ENCODES CONFORMING BYTES,
# in 3 seconds, once, at deploy time.
#
# WHY THIS EXISTS, AND WHY IT IS NOT IN e_gate_run.sh (owner directive,
# 2026-08-01).
#
# The wire audit and the black-frame decode were built as standalone
# forensics — one on 2026-07-28 to answer "is the aux view really
# inter-compressed?" from bitstream syntax rather than from the encoder's
# own logs, one on 2026-07-29 as the owner's gate after two builds
# reached the Mac flashing black. Both were folded into e_gate_run.sh the
# same week (3d09fdb7), unconditionally, when an oracle dump was 83 MB
# and walking it twice was free.
#
# It stopped being free. At 3840x2400 a 60 s run dumps 7.75 GB, and the
# two walks — parsing every slice header of 4448 pictures, then decoding
# all 4448 — took 10 min 07 s against 64 s of actual measurement. A 10x
# tax on every timing experiment, to re-prove properties that had not
# changed.
#
# WHAT THESE CHECKS ARE A PROPERTY OF (the owner's correction, and the
# whole reason this file exists): NOT the xrdp build. The rewriter logic
# is covered by CI — tests/xrdp/test_avc444_ltr.c pins it against 26
# golden-vector assertions, byte-exact, generated by ltr_splice_ref.py.
# What an ARM adds on top of that is the real stack actually producing
# bytes: this image's ffmpeg, this host's VAAPI driver, this arm's
# gfx.toml encoder_args. That is a property of the DEPLOYED PAIR, so it
# is proven ONCE when the pair is deployed and never again.
#
#   CI              the rewriter is correct                 every commit
#   arm_certify.sh  this image + config emits conforming    every deploy
#                   bytes through the real encoder
#   e_gate_run.sh   how fast it goes                        every measurement
#
# THE RULE: 3 seconds of payload after a container deploy, and NOWHERE
# ELSE. A measurement run does not dump and does not walk a dump.
#
# Usage: arm_certify.sh <arm> [port]      (port defaults from k8s/<arm>.yaml)
set -u
D=$(cd "$(dirname "$0")" && pwd)
ARM=${1:?usage: arm_certify.sh <arm> [port]}
NS=${E_NS:-bisect-matrix}
SECS=${CERT_SECS:-3}
# how long the session may take to come up before the encoder sees a
# frame; NOT part of the certified window (see the wait loop below)
LOGIN_GRACE=${CERT_LOGIN_GRACE:-30}
# The intra refresh intervals the audit checks OBSERVED cuts against.
# READ FROM THE ARM'S OWN gfx.toml, not hardcoded: the shipped default
# moved 240 -> 250 on 2026-08-08, and a certifier that assumed 240 would
# check an arm running 250 against the wrong schedule and call a correct
# stream broken. E_REFRESH still overrides, for reproducing an old run.
# The aux interval follows the main one when the key is absent, exactly
# as the loader does (BACKLOG #92).
arm_toml_int()
{
    sed -n "s/^ *$1 *= *\\([0-9][0-9]*\\).*/\\1/p" \
        "$D/gfx/$ARM.toml" 2>/dev/null | head -1
}
# The arm's CODEC MODE, read the same way. An arm configured
# avc_mode = "420" is a legitimate, shipped configuration -- an
# administrator may set it and a control arm needs it -- so the
# certifier must certify it rather than fail it (owner directive,
# 2026-08-10: "the validation machine should not bite on normal
# functionality/legit config an user or admin would set"). It gets the
# single-view gate: the AVC444 two-view assertions are about a
# long-term-reference chain across two views and a single-view stream
# has neither, so running them there tests whether the arm is AVC444,
# not whether it is correct.
arm_toml_str()
{
    sed -n "s/^ *$1 *= *\"\([^\"]*\)\".*/\1/p" \
        "$D/gfx/$ARM.toml" 2>/dev/null | head -1
}
AVC_MODE=$(arm_toml_str avc_mode)
AVC_MODE=${AVC_MODE:-444}
AUDIT_ARGS=""
[ "$AVC_MODE" = "420" ] && AUDIT_ARGS="--single-view"

REFRESH=${E_REFRESH:-$(arm_toml_int intra_refresh_frames)}
REFRESH=${REFRESH:-250}
REFRESH_AUX=${E_REFRESH_AUX:-$(arm_toml_int intra_refresh_frames_aux)}
REFRESH_AUX=${REFRESH_AUX:-$REFRESH}
CLI=${E_DISPLAY:-:94}
ORACLE_BIN=${E_ORACLE_BIN:-/opt/freerdp-vaapi/bin/xfreerdp}
CRED=${E_CRED_FILE:-/root/.oracle_cred}
SU=${E_USER:-probe444}
CERTDIR=$D/certs
SIZE=${CERT_SIZE:-1920x1080}

PORT=${2:-$(sed -n 's/^ *hostPort: *//p' "$D/k8s/$ARM.yaml" | head -1)}
[ -n "$PORT" ] || { echo "ABORT: no hostPort for $ARM" >&2; exit 1; }

fail() { echo "CERT ABORT: $*" >&2; exit 1; }

[ -x "$ORACLE_BIN" ] || fail "oracle client missing at $ORACLE_BIN"
[ -s "$CRED" ] || fail "no RDP credential at $CRED"

POD=$(kubectl -n "$NS" get pod -l "arm=$ARM" --field-selector \
        status.phase=Running -o jsonpath='{.items[0].metadata.name}' \
        2>/dev/null)
[ -n "$POD" ] || fail "no running pod for $ARM"

# The certificate is keyed to the exact thing under test. If either the
# image or the config changes, the old certificate must not be readable
# as covering the new pair -- that is the same failure the ARM_TAG /
# manifest pin guard exists for.
IMAGE=$(kubectl -n "$NS" get pod "$POD" \
        -o jsonpath='{.spec.containers[0].image}')
GFXSUM=$(sha256sum "$D/gfx/$ARM.toml" | cut -c1-16)
KEY="$IMAGE|$GFXSUM"

mkdir -p "$CERTDIR"
CERT=$CERTDIR/$ARM.cert
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

echo "certifying $ARM ($POD) — ${SECS}s of payload at $SIZE"
echo "  image  $IMAGE"
echo "  gfx    sha256:$GFXSUM"

# --- client rig: stateless, same rule as the gate (2026-07-31) ---------
XPID=$(cat "/tmp/.X${CLI#:}-lock" 2>/dev/null | tr -d ' ')
if [ -n "$XPID" ] && kill -0 "$XPID" 2>/dev/null; then
    kill -TERM "$XPID" 2>/dev/null
    for _ in 1 2 3 4 5; do kill -0 "$XPID" 2>/dev/null || break; sleep 1; done
fi
setsid Xorg "$CLI" -config "$D/../multimon_offline/xorg-dummy-2mon-4k.conf" \
    -noreset -logfile "$WORK/xorg.log" </dev/null >/dev/null 2>&1 &
XPID=$!
sleep 4

PW=$(cat "$CRED")
RDPARGS=$(printf '%s\n' "/v:127.0.0.1:$PORT" "/u:$SU" "/p:$PW" \
                        "/size:$SIZE" "/gfx:AVC444" "/cert:ignore" \
                        "/log-level:WARN")
rm -f /tmp/oracle_avc_s*.bin
setsid env DISPLAY=$CLI LD_LIBRARY_PATH=/opt/freerdp-vaapi/lib \
    FREERDP_ORACLE_DUMP=1 RDPARGS="$RDPARGS" \
    "$ORACLE_BIN" /args-from:env:RDPARGS </dev/null \
    >"$WORK/client.log" 2>&1 &
PGID=$!
unset PW RDPARGS
# $SECS is 3s of PAYLOAD, and it does not start when the client does:
# a cold pod spends seconds creating the session before the first frame
# is encoded. Measured 2026-08-01 on x014's first certification -- the
# session became available 2.9s after client launch and the client was
# killed 0.08s later, having captured nothing, which the harness then
# reported as "it is not encoding at all". That was a defect in this
# script, not a red arm. So: wait for the dump to EXIST (login is done
# and bytes are flowing), then time the window from there.
WAITED=0
while [ "$WAITED" -lt "$LOGIN_GRACE" ]; do
    ls /tmp/oracle_avc_s*.bin >/dev/null 2>&1 && break
    sleep 1
    WAITED=$((WAITED + 1))
done
if [ "$WAITED" -ge "$LOGIN_GRACE" ]; then
    cp "$WORK/client.log" "$CERTDIR/$ARM.nodump.log" 2>/dev/null
    kill -9 -- -"$PGID" 2>/dev/null
    kill -TERM "$XPID" 2>/dev/null
    fail "$ARM wrote no dump within ${LOGIN_GRACE}s of connecting — the \
session never reached the encoder; client log kept at \
$CERTDIR/$ARM.nodump.log"
fi
echo "  session up after ${WAITED}s; capturing ${SECS}s of payload"
sleep "$SECS"
kill -9 -- -"$PGID" 2>/dev/null
sleep 1
kill -TERM "$XPID" 2>/dev/null

# LOG THE SESSION OFF. A certification creates a session and the payload
# in it keeps running after the client goes away -- forever, at full
# tilt, with nothing consuming a frame (measured on x014, 2026-08-02:
# 85 % of a core 2 h 33 min after the run). The sanctioned operation is
# to log the WHOLE session off, never to pkill individual GUI processes
# in a live session (CLAUDE.md GUI lifecycle).
kubectl -n "$NS" exec "$POD" -- bash -lc \
    "pkill -TERM -u $SU -x xterm; pkill -TERM -u $SU Xorg" \
    >/dev/null 2>&1
kubectl -n "$NS" exec "$POD" -- bash -lc \
    "for i in \$(seq 1 20); do pgrep -u $SU -f sesexec >/dev/null \
     || break; sleep 1; done" >/dev/null 2>&1

# --- ENCODER INPUT PIPE GUARD (BACKLOG #103) ---------------------------
# The certification is what says "this deployed pair is fit to measure",
# and an arm whose encoder children could not get an input pipe of the
# minimum size xrdp REQUIRES is not. The requirement is 64 KiB and it is
# a measured knee, not the 1 MiB xrdp asks for: below 64 KiB the pipe
# cannot hold enough for xrdp and the encoder to run at the same time,
# so they take turns and each turn costs a pair of context switches
# (PRD FR-PROC-6 clause 4). A uid over the HOST's fs/pipe-user-pages-
# soft, without CAP_SYS_RESOURCE in the initial user namespace, is
# refused every resize and gets two pages. The standalone #103 reproducer
# measured 1688 turns per 13.8 MB picture instead of 14, taking 5.84 ms.
# xrdp does not warn about a pipe
# that is merely smaller than it asked for, so this check has no false
# alarm on a host with a lowered fs/pipe-max-size.
#
# xrdp does not and must not change a system setting to fix that (owner
# directive, 2026-08-09) -- it logs PIPE_TOO_SMALL, and the harness
# refuses. Catching it HERE, at deploy, is what stops a whole matrix of
# measurements being spent in a state where no number means anything.
PIPE_HITS=$(kubectl -n "$NS" exec "$POD" -- bash -lc \
    'sudo grep -a PIPE_TOO_SMALL /var/log/xrdp.log 2>/dev/null \
     || grep -a PIPE_TOO_SMALL /var/log/xrdp.log 2>/dev/null || true' \
    2>/dev/null | head -4)

DUMP=$(ls -S /tmp/oracle_avc_s*.bin 2>/dev/null | head -1)
if [ -z "$DUMP" ]; then
    # keep the evidence: a no-dump certification is a red result about
    # the arm, and its client log is the only thing that says why
    cp "$WORK/client.log" "$CERTDIR/$ARM.nodump.log" 2>/dev/null
    fail "$ARM produced no dump in ${SECS}s — it is not encoding at all; \
client log kept at $CERTDIR/$ARM.nodump.log"
fi
mv "$DUMP" "$WORK/cert.bin"
DUMP=$WORK/cert.bin
BYTES=$(stat -c %s "$DUMP")

{
    echo "arm:    $ARM"
    echo "mode:   AVC$AVC_MODE$([ -n "$AUDIT_ARGS" ] \
        && echo "  (single-view gate: the AVC444 two-view assertions do \
not apply)")"
    echo "image:  $IMAGE"
    echo "gfx:    sha256:$GFXSUM"
    echo "key:    $KEY"
    echo "when:   $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "window: ${SECS}s at $SIZE, $BYTES bytes"
    echo
    echo "=== encoder input pipe ==="
    if [ -n "$PIPE_HITS" ]; then
        echo "PIPE VERDICT: TOO SMALL — this arm is NOT fit to measure."
        echo "The encoder input pipe is below the 64 KiB minimum xrdp"
        echo "requires, so it cannot hold enough for xrdp and the encoder"
        echo "to run at the same time: they take turns, and each turn"
        echo "costs a pair of context switches. On this fleet that alone"
        echo "was 5.84 ms per 13.8 MB picture in the standalone pipe"
        echo "reproducer. It depresses every rate by an amount that has"
        echo "nothing to do with what is under test."
        echo
        echo "OWNER ACTION REQUIRED: raise fs/pipe-user-pages-soft on the"
        echo "HOST, or give the server CAP_SYS_RESOURCE in the initial"
        echo "user namespace, then re-certify. xrdp will not change a"
        echo "system setting itself (owner directive, 2026-08-09)."
        echo
        printf '%s\n' "$PIPE_HITS"
    else
        echo "PIPE VERDICT: OK — no PIPE_TOO_SMALL in this pod's xrdp log"
        echo "after ${SECS}s of real encoding, so every encoder child got"
        echo "an input pipe of at least the 64 KiB minimum. Above that"
        echo "the handover cost is flat (0.71 ms at 512 KiB against"
        echo "0.60 ms at 1 MiB for a 13.82 MB picture), so this is the"
        echo "whole of the requirement."
    fi
    echo
    echo "=== wire audit (--assert) ==="
    python3 "$D/../../tools/avc444_ltr_wire_audit.py" --assert \
        $AUDIT_ARGS \
        --intra-refresh "$REFRESH" --intra-refresh-aux "$REFRESH_AUX" \
        "$DUMP" "$ARM deploy certification" \
        2>&1 | tail -25
    WA=$?
    echo "wire audit exit: $WA"
    echo
    echo "=== black-frame check ==="
    python3 "$D/oracle_black_frame_check.py" "$DUMP" 2>&1 | tail -15
    echo
    echo "=== COVERAGE LIMIT OF A ${SECS}s WINDOW — read this ==="
    echo "A ${SECS}s window holds roughly 100 frames. The scheduled intra"
    echo "refresh is every $REFRESH main pictures and every $REFRESH_AUX"
    echo "aux pictures, so this certification"
    echo "typically contains NO scheduled cut, and asserts A2 (intra only"
    echo "on a scheduled index), A3 (cuts paired across views) and A4 (no"
    echo "scheduled cut skipped) VACUOUSLY. What it does prove on real"
    echo "bytes from this image: A1 no mid-stream IDR, A5 own-slot refs"
    echo "and self-marking, A6 one contiguous frame_num chain, A7 chain"
    echo "depth within bound, and that every picture decodes without a"
    echo "black frame."
    echo "The cut schedule itself is covered by CI against golden vectors"
    echo "(tests/xrdp/test_avc444_ltr.c: test_ltr_dpb_scheduled_paired_cut"
    echo "_both_modes, test_ltr_schedule_observed_vs_requested,"
    echo "test_ltr_cut_sequence_byte_exact). Do NOT lengthen this window"
    echo "to chase A2-A4 -- that is the 10x tax this file exists to"
    echo "remove, and CI already pins the logic byte-exactly."
    echo
    echo "If A3 reads SKIP above, this arm is running the SPARSE AUX"
    echo "sparse cadence: the auxiliary view is sent on only some"
    echo "frames, so the two views hold different numbers of pictures"
    echo "and comparing their ordinals is not a check that can pass or"
    echo "fail. Owner ruling, 2026-08-08. The audit decides that from"
    echo "the PICTURE COUNTS in the capture, never from a config flag,"
    echo "and A3 keeps full force at 1:1 -- which is what ships."
} > "$CERT.tmp" 2>&1

if grep -q "ASSERT VERDICT: PASS" "$CERT.tmp" \
        && grep -q "VERDICT: PASS" "$CERT.tmp" \
        && grep -q "PIPE VERDICT: OK" "$CERT.tmp"; then
    mv "$CERT.tmp" "$CERT"
    echo "CERTIFIED: $ARM -> $CERT"
    exit 0
fi
mv "$CERT.tmp" "$CERT.FAILED"
echo "NOT CERTIFIED: $ARM — see $CERT.FAILED" >&2
if grep -q "PIPE VERDICT: TOO SMALL" "$CERT.FAILED"; then
    echo "  the encoder input pipe is smaller than xrdp asked for, so no" >&2
    echo "  timing number from this arm would mean anything. This one" >&2
    echo "  needs the OWNER: raise fs/pipe-user-pages-soft on the host," >&2
    echo "  or grant CAP_SYS_RESOURCE in the initial user namespace." >&2
    echo "  xrdp does not change system settings (2026-08-09)." >&2
else
    echo "  the arm encodes non-conforming or undecodable bytes; do not" >&2
    echo "  measure it. A red result stays red." >&2
fi
exit 1
